### ISSUE TITLE
CI failure on TestEngineFetch

### ISSUE THREAD

**Issue by callahad** [suborbital/e2core#414]
Our CI workflow has started failing at:

```
--- FAIL: TestEngineFetch (0.27s)
panic: interface conversion: interface {} is *request.CoordinatedResponse, not []uint8 [recovered]
	panic: interface conversion: interface {} is *request.CoordinatedResponse, not []uint8

goroutine 31 [running]:
testing.tRunner.func1.2({0x13c9ce0, 0xc0012d0060})
	/opt/hostedtoolcache/go/1.20.2/x64/src/testing/testing.go:1526 +0x24e
testing.tRunner.func1()
	/opt/hostedtoolcache/go/1.20.2/x64/src/testing/testing.go:1529 +0x39f
panic({0x13c9ce0, 0xc0012d0060})
	/opt/hostedtoolcache/go/1.20.2/x64/src/runtime/panic.go:884 +0x213
github.com/suborbital/e2core/sat/engine2/enginetest.TestEngineFetch(0xc000170680)
	/home/runner/work/e2core/e2core/sat/engine2/enginetest/engine_test.go:159 +0x758
testing.tRunner(0xc000170680, 0x1450e80)
	/opt/hostedtoolcache/go/1.20.2/x64/src/testing/testing.go:[157](https://github.com/suborbital/e2core/actions/runs/4619606359/jobs/8168575352?pr=413#step:7:158)6 +0x10b
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.20.2/x64/src/testing/testing.go:[162](https://github.com/suborbital/e2core/actions/runs/4619606359/jobs/8168575352?pr=413#step:7:163)9 +0x3ea
FAIL	github.com/suborbital/e2core/sat/engine2/enginetest	0.484s
```

Looking at the Actions dashboard, this is a recent failure:

<img width="855" alt="Screenshot 2023-04-05 at 16 00 05" src="https://user-images.githubusercontent.com/24193/230121940-f5b4d5f9-2533-484b-97ea-471f1fa4a1b1.png">

This workflow successfully ran as part of PR #411, and we've not merged anything since then, so something external has changed to cause this failure.

**Comment by javorszky** [comment]
So that one is... basically it fetches the 1password error page, and fails and returns whatever was fetched.

The moment 1password changes the html of their error page, this will start failing.

See https://github.com/suborbital/e2core/blob/main/sat/engine2/enginetest/engine_test.go#L158-L160
